spring.application.name=DistributedMQ

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.datasource.url=jdbc:postgresql://localhost:5432/distributedmq
spring.datasource.username=postgres
spring.datasource.password=nahidwin
spring.jpa.hibernate.ddl-auto=update
